### ISSUE TITLE
Trouble Building Docker Image – Suggesting a "Deploying with Docker" Section in README

### ISSUE THREAD

**Issue by JayShoe** [directus-labs/starters#22]
Hello,

I’ve been experimenting with the Next.js starter as part of a proof of concept. My goal is to package the project into a Docker image and eventually deploy it to [[Railway](https://railway.app/)]. I already have a Directus instance up and running on Railway. My next goal is to get the unaltered starter kit deployed. 

I've managed to get the dev version working locally with `pnpm install` and `pnpm run dev` using the deployed instance of Directus as the API. However, when I try to build a Docker image of this starter, I run into the following error:

```
=> ERROR [deps 3/3] RUN     if [ -f yarn.lock ]; then yarn --frozen-lockfile;     elif [ -f package-lock.json ];  2.1s
------
 > [deps 3/3] RUN     if [ -f yarn.lock ]; then yarn --frozen-lockfile;     elif [ -f package-lock.json ]; then npm ci --legacy-peer-deps;     elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile;     elif [ -f bun.lockb ]; then bun install --frozen-lockfile;     else echo "Lockfile not found." && exit 1;     fi:
Error: Cannot find matching keyid: ...
```

It looks like Corepack is failing during installation with a signature verification error.

---

### Suggestion:

Would it be possible to include a section in the `README.md` for the project titled **“Deploying with Docker”**, specifically for users trying to build and run the starter kits inside containers?

Even just a simple working example of a `Dockerfile` for local development and another for production would go a long way in helping folks like me get up and running quickly with Docker and services like Railway.

Thanks so much for all the work on this starter — it’s a great project!

Best,  
Jay

**Comment by bryantgillespie** [comment]
Are you referring to the Dockerfile within the Next.js directory?

**Comment by JayShoe** [comment]
Yes, that's the one I'm testing. 
https://github.com/directus-labs/starters/blob/main/simple-cms/nextjs/Dockerfile

I clone the repo, go into that folder, and run a command like this. 
`docker build -f Dockerfile -t simple-cms-nextjs-dev .`

I wind up with the error stated above.

**Comment by bryantgillespie** [comment]
Gotcha. Yeah sorry about the issues there - we'll add that to the list to review. I believe it was a holdover from the Next.js boilerplate we used and I've not actually spent a ton of time testing Nextjs within Docker.

**Comment by JayShoe** [comment]
Hi Bryant, no worries at all -- I totally understand.

The `Dockerfile` being inherited from the Next.js starter makes complete sense. It sounds like this might be a known issue with `Corepack`, and that it can sometimes be resolved by bypassing it and using `pnpm` directly. I'm still digging into it myself, but it’s a bit above my head for now.

I was able to deploy Directus on Railway using [[this Directus template](https://railway.com/template/2fy758)]. The process was pretty smooth overall, though I did need to temporarily disable the pressure limiter to get the CMS template to load successfully with the directus-template-cli.

Just an idea for improving the developer experience: it might be helpful to publish Docker images for these builds on Docker Hub. This would be especially useful for testing across different starters (and Directus setups in general). I also know that there is a lot of construction going on right now too. 

One approach could be a single image running multiple starters (`directus-labs/starters`). Each starter could be launched on different ports (e.g., `3000`, `3001`, `3100`, `3101`). Alternatively of course you would have separate images for each variant (e.g., `directus-labs/simple-cms-nextjs`, `directus-labs/simple-cms-astro`, etc.). It could work -- sounds like a lot, but maybe automation could help here.

Happy to help test or contribute however I can!

**Comment by JayShoe** [comment]
I was able to get the starter deployed on Vercel pretty easily.

I could see `directus-template-cli` also cloning a copy of the repo to disk for running with `pnpm`, but in that case, users would need to `cd` into the frontend folder, run `pnpm install`, then `pnpm run dev`. That assumes Node and other dev tools are already installed - which might not always be the case.

Personally, I’ve found working with `docker-compose.yml` and Directus to be super intuitive, and I think there’s a great opportunity to bring that same simplicity to the frontend setup. Ideally, I’d love to spin up both the backend and frontend with a single `docker-compose up`.

Each starter (like `simple-cms`, `crm`, etc.) could include its own `docker-compose.yml` with optional frontend services. For example:

```yaml
version: "3.8"

services:
  database:
    image: postgis/postgis:13-master
    # platform: linux/amd64  # Uncomment if running on Apple M1/M2
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET: "replace-with-secure-random-value"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      # PUBLIC_URL: "https://directus.example.com"

  nextjs:
    build:
      context: ./frontend-nextjs
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_DIRECTUS_URL: "http://localhost:8055"
    depends_on:
      - directus
    profiles:
      - next

  astro:
    build:
      context: ./frontend-astro
    ports:
      - "3001:3001"
    environment:
      PUBLIC_DIRECTUS_URL: "http://localhost:8055"
    depends_on:
      - directus
    profiles:
      - astro

  nuxt:
    build:
      context: ./frontend-nuxt
    ports:
      - "3002:3000"
    environment:
      PUBLIC_DIRECTUS_URL: "http://localhost:8055"
    depends_on:
      - directus
    profiles:
      - nuxt
```

I imagine that a `Dockerfile` or `entrypoint.sh` script could also run the `npx directus-template-cli` to apply the template. 

**To launch Directus + Next.js:**
```bash
docker-compose --profile next up
```

**To launch Directus + Astro:**
```bash
docker-compose --profile astro up
```

**To launch Directus + Nuxt:**
```bash
docker-compose --profile nuxt up
```

If you want to run **all frontends and Directus** at the same time:
```bash
docker-compose up
```

Using Compose profiles or just commenting out the frontends you don’t need would keep things flexible. That way, devs with just Docker Desktop installed could get up and running quickly - and start building content right away. At my company we already use Directus as a "desktop app" using docker, and this could be an extension of that concept. 

Github actions could almost certainly run a deployment action for the myriad of frontends. 

Great work regardless! I'm running now. Cheers and rock on!
